### ISSUE TITLE
Replace Globus references in package description & summary text

### ISSUE THREAD

**Issue by matyasselmeci** [gridcf/gct#13]
The spec files (and debian packages?) have text that references the Globus Toolkit, Globus Alliance, and a few other things that we should replace with our own language and names.

**Comment by fscheiner** [comment]
We should also include Autoconf input files, e.g.:

[`./configure.ac`](https://github.com/gridcf/gct/blob/master/configure.ac):
```
[...]
AC_INIT([globus_toolkit], gtreleasebuild, [https://github.com/globus/globus-toolkit/issues])

m4_define([short_version], [m4_substr(AC_PACKAGE_VERSION, [0],
    m4_index(AC_PACKAGE_VERSION, [.]))])
AC_PREFIX_DEFAULT([/usr/local/globus-]short_version)
[...]
```
...to maybe:
```
[...]
AC_INIT([gct], gtreleasebuild, [https://github.com/gridcf/gct/issues])

m4_define([short_version], [m4_substr(AC_PACKAGE_VERSION, [0],
    m4_index(AC_PACKAGE_VERSION, [.]))])
AC_PREFIX_DEFAULT([/usr/local/gct-]short_version)
[...]
```

But this also comes for a price as long as Globus is still providing patches, because if we e.g. change the issue URL or package name or the content of `AC_PREFIX_DEFAULT` and Globus changes the same files later we need to be careful not to reintroduce their naming and references when merging their changes (e.g. like Mattias @ellert  did in https://github.com/gridcf/gct/commit/babc258db75d72889bec87a0f2838535afeb7c76).

**Comment by ellert** [comment]
The issue URLs in the AC_INIT macros in the configure.ac files were changed in PR #27, whic also changed the descriptions in the pkg-config (.pc) files. The descriptions in the debian packaging files are changed in PR #31.

**Comment by fscheiner** [comment]
This issue looks fixed to me, so I'm closing it.
