### ISSUE TITLE
globus-gridftp, globus-gram5 and globus-gsi not found

### ISSUE THREAD

**Issue by middlestone** [gridcf/gct#181]
I follow the quick start to install globus toolkit, and find that link http://www.globus.org/ftppub/gt6/installers/repo/globus-toolkit-repo-latest.noarch.rpm does not exist any more. so I download it from https://downloads.globus.org/toolkit/gt6/stable/installers/repo/rpm/globus-toolkit-repo-latest.noarch.rpm, but when I run

yum install globus-gridftp globus-gram5 globus-gsi myproxy myproxy-server myproxy-admin

it shows error.
...
No match for argument: globus-gridftp
No match for argument: globus-gram5
No match for argument: globus-gsi

Does any one can tell me what's wrong? thanks in advance.

**Comment by fscheiner** [comment]
The actual problem is that the EPEL and Fedora repositories do not contain these "virtual" packages. We are in the process of updating our documentation to reflect that. Plus the links to the Globus repos are dated. The GCT packages are available from EPEL or Fedora repositories for Red Hat-like Linux distributions.

Please have a look at #176 and https://github.com/gridcf/gct-docs/pull/27 which should basically fix that issue and this one here, too.

Instead of installing the "virtual" packages, you need to install the actual packages, like so:
```
root# yum install \
    globus-gridftp-server-progs globus-gass-copy-progs globus-common-progs globus-gsi-cert-utils-progs globus-gss-assist-progs globus-proxy-utils \
    globus-gatekeeper globus-gram-job-manager globus-gram-job-manager-scripts globus-gram-job-manager-fork-setup-poll globus-gram-client-tools globus-gass-cache-program globus-gass-server-ez-progs \
    globus-simple-ca \
    myproxy myproxy-server myproxy-admin
```
...which is equivalent to the command above. For the "globus-gsi" part, only "globus-simple-ca" is installed, because all other "globus-gsi" dependencies are already installed further above.

I'm closing this one here now and mark it as duplicate (of #176).
