### ISSUE TITLE
[Discussion] Confused about the mechanism of LRM adapter

### ISSUE THREAD

**Issue by iWangJiaxiang** [gridcf/gct#66]
Hi, everyone. I'm confused about the mechanism of LRM adapter.

As we know, Local Resource Manager(LRM) adapter is the bridge between GCT and local batch system such as PBS, Slurm, etc.. When I tried to use PBS batch system with Globus LRM for PBS in a grid, I found 
the `globus-job-get-output` cmd didn't work after the job was done. Below is the output:

`/var/spool/pbs/mom_priv/jobs/128.pbsserver.SC: line 30: /home/globususer/.globus/.gass_cache/local/md5/b0/1977efe2641d7d7125768fae62a986/md5/8e/68009ac6a0caf05dc69d88b3884d51/data: No such file or directory`

My cluster environment is
1 PBS master node with Globus LRM adapter (only managing and scheduling  jobs)
8 PBS computing nodes (only executing jobs)
All of them are running on CentOS7

Why it happenned? I thought it was just a bug. But it turned out a 'feature' of LRM Adapter after my research. XD

The reason why I got errors is because when I run  `globus-job-get-output`, the LRM Adapter would submit a new fetch job to LRM such as PBS to fetch the output file, which would be executed on computing node. So that is the problem. My master node holding the job output files was set not to execute jobs and the computing node executing the fetch job didn't hold any output files...

So I am wondering why the mechanism of Globus LRM Adapter is like that (by submitting new fetch job) ? Why not just read the local output files on master node? Is there an elegant way to use the mechanism?

Thank you.

**Comment by fscheiner** [comment]
@iWangJiaxiang:
Not sure if this is still relevant to you, but I could imagine that it's done like that, because it allows to access the output files (here you meant files for job stdout and stderr, right?) with the job submission interface of the LRM alone.

In addition, looking into [gridcf/gct/gram/client_tools/source/globus-job-get-output.in](https://github.com/gridcf/gct/blob/master/gram/client_tools/source/globus-job-get-output.in#L48..L49), it specifically says that `globus-job-get-output` retrieves stdout and/or stderr from a job that was started with `globus-job-submit` which might default to a configuration for the stdout/stderr files that might be incompatible with your configuration. Though I have to say that [the defaults for this configuration](https://github.com/gridcf/gct/blob/master/gram/client_tools/source/globus-job-submit.txt#L89..L103) - "[...] file is interpreted to be on a file system local to the LRM [...]" sounds to me like it assumes the files are in reach of the LRM (i.e. like your described configuration), but in contrast the longer description of `globus-get-job-output` on https://gridcf.org/gct-docs/latest/gram5/pi/index.html#gram5-cmd-globus-job-get-output sounds like it actually retrieves (as in downloads) these stdout/stderr files from the host that executed the corresponding job (not sure what would happen for a multi-host job) and displays its contents. The latter is what you experienced I think.

I think this is maybe better discussed on our mailing list for discussions: [discuss@gridcf.org](https://mailman.egi.eu/mailman/listinfo/discuss), though no guarantee that you'll get a better answer there.

**Comment by msalle** [comment]
Perhaps the `-s` option for the `-stdin`, `-stdout` and `-stderr` options to [globus-job-submit](https://gridcf.org/gct-docs/latest/gram5/pi/index.html#gram5-cmd-globus-job-submit) could help? It says the default is to assume `-l` meaning they're left on the LRMS headnode.
I think the setup assumes a shared (NFS) homedirectory between the head node and the workernodes, which would mean you could get the output from either.

**Comment by fscheiner** [comment]
> Perhaps the `-s` option for the `-stdin`, `-stdout` and `-stderr` options to [globus-job-submit](https://gridcf.org/gct-docs/latest/gram5/pi/index.html#gram5-cmd-globus-job-submit) could help? It says the default is to assume `-l` meaning they're left on the LRMS headnode.

On second thought: So `globus-job-submit` expects the files for `stdin`, `stdout` and `stderr` either on (1) the host that hosts the LRM (e.g. Torque) - i.e. the headnode - or (2) on the client's host, from where it is staged in, but to where? The headnode or the workernode(s) that are used for the job?

> I think the setup assumes a shared (NFS) homedirectory between the head node and the workernodes, which would mean you could get the output from either.

That would void my question above, because the shared FS would unify the headnode and the workernodes for file storage. And this is also vastly the default, i.e. to have a FS shared throughout a cluster.

@iWangJiaxiang: BTW why did you deviate from that common solution (i.e. FS shared between head node and worker nodes)?

**Comment by fscheiner** [comment]
I'm closing this issue now because there seems to be no further interest in this question. Please reopen if needed.
